# Site settings
url: 'https://hgriff0n.github.io/spero-lang'
baseurl: '/spero-lang/'
repository: hGriff0n/spero-lang
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

# author:
#   name: 'Grayson Hooper'
#   email: ghooper96@gmail.com
#   twitter_username: ghooper96
#   github_username:  hgriff0n
#   linkedin_username:  hgriff0n

paginate: 5

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
