# Site settings
title: Spero
email: ghooper96@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  This is the website for the Spero programming language. Currently
  Spero is still in the design and development stages, but it will
  be a functional, OOP-styled static programming language

baseurl: "/spero-lang/" # the subpath of your site, e.g. /blog/
url: "https://hgriff0n.github.io/spero-lang" # the base hostname & protocol for your site
twitter_username: ghooper96
github_username:  hGriff0n

# Exclude from Build
exclude:
    - ".git"
    - "serve.bat"
    - "mkpost.rb"

gems:
    - jekyll-paginate
    #- jekyll-feed